logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
spring:
  sql:
    init:
      mode: never
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/organic_shop?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    hidden-method:
      filter:
        enabled: true
